In [13]:
import pandas as pd

pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

In [3]:
df = pd.read_csv(r"D:\FData\All_Top_5_League\2024_25\event_data\Top5_League_2024_25_event_data.csv")

C:\Users\h\AppData\Local\Temp\ipykernel_27620\1088915067.py:1: DtypeWarning: Columns (32) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(r"D:\FData\All_Top_5_League\2024_25\event_data\Top5_League_2024_25_event_data.csv")

In [5]:
df = df[[
        'eventId', 'minute', 'second', 'type', 'outcomeType', 'x', 'y',
        'playerName', 'shirtNo', 'position', 'age', 'teamName',
        'oppositionTeamName', 'h_a', 'matchId', 'venueName',
]]

In [8]:
df = df[df['type'].isin(['OffsideGiven', 'OffsidePass', 'OffsideProvoked'])]

In [10]:
offside_provoked = df[df['type']=='OffsideProvoked']
offside_caught = df[df['type']=='OffsideGiven']

In [ ]:
df = df[[
        'eventId', 'minute', 'second', 'type', 'outcomeType', 'x', 'y',
        'playerName', 'shirtNo', 'position', 'age', 'teamName',
        'oppositionTeamName', 'h_a', 'matchId', 'venueName',
]]

df = df[df['type'].isin(['OffsideGiven', 'OffsidePass', 'OffsideProvoked'])]

offside_provoked = df[df['type']=='OffsideProvoked']
offside_caught = df[df['type']=='OffsideGiven']

In [21]:
offside_provoked_summary = (
    offside_provoked
    .groupby(['matchId', 'teamName', 'oppositionTeamName'])
    .size()
    .reset_index(name='offsides_provoked')
    .sort_values(by='offsides_provoked', ascending=False)
    .reset_index(drop=True)
)
offside_provoked_summary = offside_provoked_summary[['teamName', 'offsides_provoked', 'oppositionTeamName']]
offside_provoked_summary = offside_provoked_summary.rename(columns={'oppositionTeamName': 'against'})

offside_provoked_summary.head(20)

               teamName  offsides_provoked              against
0             Barcelona                 12          Real Madrid
1             Barcelona                 11             Mallorca
2             Barcelona                 11     Deportivo Alaves
3             Barcelona                 11     Deportivo Alaves
4             Barcelona                 10              Osasuna
5             Stuttgart                  9           Leverkusen
6              Valencia                  9              Leganes
7                Getafe                  8             Mallorca
8     Borussia Dortmund                  8        Werder Bremen
9             Marseille                  8                  PSG
10             AC Milan                  8             Cagliari
11            Stuttgart                  8  Borussia M.Gladbach
12               Fulham                  7    Nottingham Forest
13  Eintracht Frankfurt                  7             Freiburg
14        Saint-Etienne                  7                 Lens
15              Venezia                  7                Genoa
16        Real Sociedad                  7              Leganes
17            Barcelona                  7           Villarreal
18            Barcelona                  7               Girona
19                Lecce                  7             AC Milan

In [23]:
offside_caught_summary = (
    offside_caught
    .groupby(['matchId', 'playerName', 'oppositionTeamName'])
    .size()
    .reset_index(name='offsides_provoked')
    .sort_values(by='offsides_provoked', ascending=False)
    .reset_index(drop=True)
)
offside_caught_summary = offside_caught_summary[['playerName', 'offsides_provoked', 'oppositionTeamName']]
offside_caught_summary = offside_caught_summary.rename(columns={'oppositionTeamName': 'against'})

offside_caught_summary.head(20)

             playerName  offsides_provoked              against
0         Kylian Mbappé                  8            Barcelona
1            Akor Adams                  6            Marseille
2          Vedat Muriqi                  5            Barcelona
3       Patrick Cutrone                  5    Parma Calcio 1913
4          Junior Adamu                  5  Eintracht Frankfurt
5       Roberto Piccoli                  5             AC Milan
6   Rémy Labeau Lascary                  5                Brest
7          Zito Luvumbo                  4              Udinese
8          M'Bala Nzola                  4                  PSG
9          Junior Adamu                  4               Bochum
10      Serhou Guirassy                  4        Werder Bremen
11        Sidiki Cherif                  4                 Lens
12          Kai Havertz                  4              Chelsea
13     Christantus Uche                  4        Athletic Club
14           Chris Wood                  4               Fulham
15            Dan Ndoye                  4                Genoa
16     Benedikt Pichler                  4               Bochum
17       Nathan Ngoumou                  4            Stuttgart
18        Thierno Barry                  4           Las Palmas
19        Kylian Mbappé                  4             Valencia